---
title: "Analysis of Longevity"
author: "Ryan Abdella"
date: "January 15, 2015"
output:
  html_document:
    css: ~/Dropbox/Ryan/Food_Optimization/Results/foghorn_edited.css
---


```{r, warning = F, message = F, echo = F}

source("./wMT_fxns.R")
library("dplyr")
library("ggplot2")

experiment <- paste("./p0", j, "_", k, "mgmL", sep = "")
source(paste(experiment, ".R", sep = ""))

data.loc <- paste("../Data/Raw/p0", j, "_", k, "mgmL/", sep = "")

```


```{r, warning = F, message = F, echo = F}

files <- dir(path = data.loc, plateID, full.names = T)
data.df <- ldply(files, processMicrotrackerReport) %>% filter(time < 9)
data.df$day <- rep(1:(length(files)), each = nstrains * replicates * data_points_per_day)

```

## Raw Activity

```{r, warning = F, message = F, echo = F}

ggplot(data.df) + aes(x=day, y=activity) + geom_point() + facet_grid(row~col) +
  labs(x="Time (day)", y="Activity")

```


```{r, warning = F, message = F, echo = F}

combined.df <- aggregate(activity ~ row + col + day, data = data.df, sum)

```


```{r, warning = F, message = F, echo = F}

combined.df <- combined.df[order(combined.df$col, combined.df$row, combined.df$day), ]
data.df <- data.df[order(data.df$col, data.df$row, data.df$day), ]

combined.df$strain <- rep(strains, each = replicates * length(files))
data.df$strain <- rep(strains, each = replicates * length(files) * data_points_per_day)

```


```{r, warning = F, message = F, echo = F}

combined.df$activity[(combined.df$col %in% colRemove)] <- NA
data.df$activity[(data.df$col %in% colRemove)] <- NA

```


```{r, warning = F, message = F, echo = F}

combined.df <- combined.df %>%
  group_by(col, row) %>%
  mutate(norm.act = 100 * activity / max(activity, na.rm = T))

data.df <- data.df %>%
  group_by(col, row) %>%
  mutate(norm.act = 100 * activity / max(activity, na.rm = T))

```

## Binned Data

```{r, warning = F, message = F, echo = F}

ggplot(data.df) + aes(x=factor(day), y=norm.act) + ylim(0, 100) + geom_boxplot() + facet_grid(row~col) +
  labs(x="Time (day)", y="Activity")

```

## Combined Data

```{r, warning = F, message = F, echo = F}

ggplot(combined.df) + aes(x = day, y = norm.act) + ylim(0, 100) + geom_point() + facet_grid(row ~ col) +
  labs(x = "Time (day)", y = "Activity")

```


```{r, warning = F, message = F, echo = F}

gompertz <- function(input, df, name) {
  sum(((100*100^((input[1]/input[2])*(1-exp(input[2]*df$day[df$strain == name]))))-df$norm.act[df$strain == name])^2)
}

weibull <- function(input, df, name) {
  sum(((100*100^(-((df$day[df$strain == name]/input[2])^input[1])))-df$norm.act[df$strain == name])^2)
}

twoplog <- function(input, df, row, col) {
  sum(((100/(1 + ((df$day[df$row == row & df$col == col]/input[2])^input[1])))-df$norm.act[df$row == row & df$col == col])^2)
}

threeplog <- function(input, df, name) {
  sum(((100*100^(-input[2]*df$day[df$strain == name] - (input[2]/input[3])*ln((input[1] - (input[2] - input[1])*exp(-input[3]*df$day[df$strain == name]))/input[2])))-df$norm.act[df$strain == name])^2)
}

test3 <- combined.df %>%
  group_by(col, row) %>%
  summarize(cpar = nlm(twoplog, c(2, 2), combined.df, row, col)[["estimate"]][1])

twoplog2 <- formula(norm.act ~ 100/(1 + ((day/b)^c)))

nls(norm.act ~ selfStart(~ 100 / (1 + ((day / b) ^ c)), function(mCall, data, LHS)
  {
  xy <- sortedXyData(mCall[["day"]], LHS, data)
  if(nrow(xy) < 4) {
    stop("Too few distinct x values to fit a logistic")
  }
  z <- xy[["y"]]
  if (min(z) <= 0) { z <- z + 0.05 * max(z) } # avoid zeroes
  z <- z/(1.05 * max(z))              # scale to within unit height
  xy[["z"]] <- log(z/(1 - z))         # logit transformation
  aux <- coef(lm(x ~ z, xy))
  parameters(xy) <- list(xmid = aux[1], scal = aux[2])
  pars <- as.vector(coef(nls(y ~ 100 / (1 + exp((xmid - x)/scal)),
                             data = xy, algorithm = "plinear")))
  setNames(c(pars[3], pars[1], pars[2]),
           mCall[c("Asym", "xmid", "scal")])
  }, c("b", "c"))

for (i in combined.df$row) {
  for (j in combined.df$col) {
    
  }
}

```

```{r, warning = F, message = F, echo = F}

save(combined.df, file = paste("../Data/Raw/p0", j, "_", k, "mgmL/Combined_p0", j, "_", k, "mgmL.Rda", sep = ""), ascii = TRUE)
save(data.df, file = paste(data.loc, "Separate_p0", j, "_", k, "mgmL.Rda", sep = ""), ascii = TRUE)

```

